const DependencySymbols = {
  Application: Symbol.for("Application"),
  ApplicationConfig: Symbol.for("ApplicationConfig"),
  Pool: Symbol.for("Pool"),
  TodoServer: Symbol.for("TodoServer"),
  AuthController: Symbol.for("AuthController"),
  HealthController: Symbol.for("HealthController"),
  PasswordResetController: Symbol.for("PasswordResetController"),
  ProfileController: Symbol.for("ProfileController"),
  TodoController: Symbol.for("TodoController"),
  UserController: Symbol.for("UserController"),
  AuthenticateToken: Symbol.for("AuthenticateToken"),
  ErrorMiddleware: Symbol.for("ErrorMiddleware"),
  RateLimiters: Symbol.for("RateLimiters"),
  AuthRouter: Symbol.for("AuthRouter"),
  ProfileRouter: Symbol.for("ProfileRouter"),
  TodoRouter: Symbol.for("TodoRouter"),
  UserRouter: Symbol.for("UserRouter"),
  OutboxRepository: Symbol.for("OutboxRepository"),
  PasswordResetRepository: Symbol.for("PasswordResetRepository"),
  SystemRepository: Symbol.for("SystemRepository"),
  TodoRepository: Symbol.for("TodoRepository"),
  UserRepository: Symbol.for("UserRepository"),
  AuthService: Symbol.for("AuthService"),
  AuthorizationService: Symbol.for("AuthorizationService"),
  HealthService: Symbol.for("HealthService"),
  OutboxPublisherService: Symbol.for("OutboxPublisherService"),
  TodoService: Symbol.for("TodoService"),
  TokenService: Symbol.for("TokenService"),
  UserService: Symbol.for("UserService"),
  TaskEventFactory: Symbol.for("TaskEventFactory"),
  TaskEventPublisher: Symbol.for("TaskEventPublisher"),
  UuidGenerator: Symbol.for("UuidGenerator"),
  MigrationRunner: Symbol.for("MigrationRunner"),
} as const;

export default DependencySymbols;
